"use client"
import { BrowserRouter } from "react-router-dom";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BrowserRouter>
        <body className={inter.className}>{children}</body>
      </BrowserRouter>
    </html>
  );
}
